settings/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

import siriset_login.urls as login
import siriset_profile.urls as profile
import siriset_research_apply.urls as applyr
import siriset_research_approve.urls as approver
import siriset_research_view_approved.urls as viewappr
import siriset_logbook.urls as log
import siriset_defense_propose.urls as defense
import siriset_defense_schedule.urls as dsched
import siriset_scipaper_submit.urls as scipaper
import siriset_seminar_insert.urls as seminar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include((login, login), namespace='login')),
    path('profile/', include((profile, profile), namespace='profile')),
    path('apply-research/', include((applyr, applyr), namespace='apply-research')),
    path('approve-research/', include((approver, approver), namespace='approve-research')),
    path('view-approved/', include((viewappr, viewappr), namespace='view-approved')),
    path('logbook/', include((log, log), namespace='logbook')),
    path('propose-defense/', include((defense, defense), namespace='defense')),
    path('defense-schedule/', include((dsched, dsched), namespace='defense-schedule')),
    path('submit-paper/', include((scipaper, scipaper), namespace='scipaper')),
    path('insert-seminar/', include((seminar, seminar), namespace='seminar')),
    path('', RedirectView.as_view(url='login/student', permanent=True), name='index'),
]

siriset_logbook/urls.py
from django.conf.urls import url
from .views import index, logbook, approve, add, add_form
#url for app

app_name = 'log'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^view/$', logbook, name='view'),
    url(r'^add/$', add, name='add'),
    url(r'^add-form/$', add_form, name='add-form'),
    url(r'^approve/$', approve, name='approve'),
]

siriset_logbook/models.py
from django.db import models

# Create your models here.
class Logbook(models.Model):
    logbook_id = models.IntegerField(primary_key=True)
    datetime = models.DateField()
    location = models.CharField(max_length=50)
    summary = models.CharField(max_length=500)
    plan = models.CharField(max_length=500)
    research = models.ForeignKey('siriset_research_apply.Research', models.DO_NOTHING)
    supervisor = models.ForeignKey('siriset_login.Supervisor', models.DO_NOTHING)
    status = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'logbook'

siriset_logbook/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.db import connection, transaction
from django.http import JsonResponse
from django.urls import reverse

response = {}

@csrf_exempt
def index(request):
    cursor = connection.cursor()

    if request.session['role'] == "student":
        sql = "SELECT rt.research_type_name, r.topic, r.research_id\
            FROM research r, research_type rt\
            WHERE r.research_type_id = rt.research_type_id and r.research_id = %s"
        cursor.execute(sql, [request.session["research_id"]])

    elif request.session['role'] == "supervisor":
        sql = "SELECT u.name, sp.degree, rt.research_type_name, r.topic, r.research_id\
            FROM research r, research_type rt, user_ u, student s, study_program sp\
            WHERE r.research_type_id = rt.research_type_id and r.student_npm = s.npm\
            and s.sso_username = u.sso_username and s.program_id = sp.program_id\
            and r.research_id = %s"
        cursor.execute(sql, [request.session["research_id"]])

    research = dictfetchall(cursor)[0]

    sql = "SELECT l.logbook_id, l.datetime, l.location, l.summary, l.plan, l.status\
        FROM logbook l WHERE l.research_id = %s"

    cursor.execute(sql, [request.session["research_id"]])
    logbook = dictfetchall(cursor)

    response['author'] = "si-riset"
    response['research'] = research
    response['logbook'] = logbook

    return render(request, 'logbook_view.html', response)

@csrf_exempt
def logbook(request):
    print("masuk logbook")
    if request.method == 'POST':
        request.session["research_id"] = request.POST['id']

    return JsonResponse({'redirect_url': '/logbook/'})

@csrf_exempt
def approve(request):
    if request.method == 'POST':
        logbook_id = request.POST['id']

    cursor = connection.cursor()

    sql = "UPDATE logbook SET status = 'approved' WHERE logbook_id = %s"
    cursor.execute(sql, [logbook_id])

    return JsonResponse({'redirect_url': '/logbook/'})

def add_form(request):

    return render(request, 'logbook_add.html', response)

@csrf_exempt
def add(request):
    print("keluar ga")
    if request.method == 'POST':
        print(request.POST)
        date = request.POST['date']
        location = request.POST['loc']
        summary = request.POST['summary']
        plan = request.POST['plan']

    research_id = request.session["research_id"]

    cursor = connection.cursor()

    sql = "SELECT supervisor_id FROM research WHERE research_id = %s"

    cursor.execute(sql, [research_id])
    supervisor_id = dictfetchall(cursor)[0]['supervisor_id']

    sql = "INSERT INTO logbook (logbook_id, datetime, location, summary, plan, research_id,\
        supervisor_id, status) VALUES (nextval('LogbookId'), %s, %s, %s, %s, %s, %s, 'not approved')"

    cursor.execute(sql, [date, location, summary, plan, research_id, supervisor_id])

    return JsonResponse({'redirect_url': '/logbook/'})

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

siriset_logbook/templates/logbook_add.html
{% extends "layout/base.html" %}

{%block content%}
<div class="py-3">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
      </br>
        <p class="lead py-0">Add Logbook Entry</p>
        <form id="add-entry" action="#">
            <label for="field_date">Date:</label>
            <input id="field_date" type="date" name="date" class="form-control"/>
            <label for="field_location">Location:</label>
            <input id="field_location" type="text" name="location" class="form-control"/>
            <label for="field_summary">Summary:</label>
            <input id="field_summary" type="text" name="summary" class="form-control"/>
            <label for="field_plan">Plan:</label>
            <input id="field_plan" type="text" name="plan" class="form-control"/><br>
            <button style="font-size: 90%" class="submit btn btn-outline-primary" type="submit">Add</button>
        </form>
      </div>
    </div>
  </div>
</div>

<script>

var addEntry = function(date, loc, summary, plan) {
    console.log("Here?")
    $.ajax({
        method: "POST",
        url: "{% url 'logbook:add' %}",
        data: {date: date, loc: loc, summary: summary, plan: plan},
        success : function (response) {
            window.location.href = response.redirect_url;
        },
        error : function (error) {
            alert(error.responseText);
        }
    });
};

$("#add-entry").on("submit", function (event) {
   date = $("#field_date").val()
   location_ = $("#field_location").val()
   summary = $("#field_summary").val()
   plan = $("#field_plan").val()

   if(date === "" || location_ === "" || summary === "" || plan === "") {
       alert("Field cannot be empty.");
       return false;
   }

   addEntry(date, location_, summary, plan)
   event.preventDefault();
});

</script>

{% endblock %}

siriset_logbook/templates/logbook_view.html
{% extends "layout/base.html" %}

{%block content%}
  <div class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
        </br>
          <p class="lead py-0">Research Logbook</p>
          <div class="student">
          <p style="font-size: 90%;" class="lead py-0">Research Type: {{ research.research_type_name }}
          <br>Topic: {{ research.topic }}</p></div>
          <div class="supervisor">
          <p style="font-size: 90%; text-transform: capitalize;" class="lead py-0">Student Name: {{ research.name }}
              <br>Degree: {{ research.degree }}
              <br>Research Type: {{ research.research_type_name }}
              <br>Topic: {{ research.topic }}</p></div>
          <div class="student">
          <a href="{% url 'logbook:add-form' %}" style="font-size: 90%" class="btn btn-outline-primary">Add Entry</a></div>
        </div>
      </div>
    </div>
  </div>
  <div class="px-1">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <table class="table">
            <thead> </thead>
            <tbody>
              <tr>
                  <th>Date</th>
                  <th>Location</th>
                  <th>Summary</th>
                  <th>Plan</th>
                  <th><div class="student">Status</div></th>
              </tr>
              {% for data in logbook %}
              <tr>
                  <td>{{ data.datetime }}</td>
                  <td>{{ data.location }}</td>
                  <td>{{ data.summary }}</td>
                  <td>{{ data.plan }}</td>
                  <td>
                      <div class="student">{{ data.status }}</div>
                      <div class="supervisor"><button id="{{ data.logbook_id }}" data-status="{{ data.status }}" onClick=approve({{ data.logbook_id }}) style="font-size: 90%" class="btn btn-outline-primary approve-button">Approve</button></div>
                  </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

<script>

// Show div html based on role
var role = "{{ request.session.role }}";
console.log(role)
if (role === "supervisor"){
    $("div.supervisor").show();
} else if (role === "student"){
    $("div.student").show();
}

$(".approve-button").each(function(index) {
  if ($(this).attr("data-status") === "approved"){
      $(this).prop("disabled", true);
  }
});

var approve = function(id) {
    $.ajax({
        method: "POST",
        url: "{% url 'logbook:approve' %}",
        data: {id: id},
        dataType: 'json',
        success : function (response) {
            alert("Approved.");
            $("#" + id).prop("disabled", true);
        },
        error : function (error) {
            alert(error.responseText);
        }
    });
}
</script>
{% endblock %}