settings/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

import siriset_login.urls as login
import siriset_profile.urls as profile
import siriset_research_apply.urls as applyr
import siriset_research_approve.urls as approver
import siriset_research_view_approved.urls as viewappr
import siriset_logbook.urls as log
import siriset_defense_propose.urls as defense
import siriset_defense_schedule.urls as dsched
import siriset_scipaper_submit.urls as scipaper
import siriset_seminar_insert.urls as seminar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include((login, login), namespace='login')),
    path('profile/', include((profile, profile), namespace='profile')),
    path('apply-research/', include((applyr, applyr), namespace='apply-research')),
    path('approve-research/', include((approver, approver), namespace='approve-research')),
    path('view-approved/', include((viewappr, viewappr), namespace='view-approved')),
    path('logbook/', include((log, log), namespace='logbook')),
    path('propose-defense/', include((defense, defense), namespace='defense')),
    path('defense-schedule/', include((dsched, dsched), namespace='defense-schedule')),
    path('submit-paper/', include((scipaper, scipaper), namespace='scipaper')),
    path('insert-seminar/', include((seminar, seminar), namespace='seminar')),
    path('', RedirectView.as_view(url='login/student', permanent=True), name='index'),
]

siriset_logbook/urls.py
from django.conf.urls import url
from .views import index, logbook, approve, add, add_form
#url for app

app_name = 'log'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^view/$', logbook, name='view'),
    url(r'^add/$', add, name='add'),
    url(r'^add-form/$', add_form, name='add-form'),
    url(r'^approve/$', approve, name='approve'),
]

siriset_research_view_approved/urls.py
from django.conf.urls import url
from .views import index
#url for app

app_name = 'viewappr'

urlpatterns = [
    url(r'^$', index, name='index'),
]

siriset_research_view_approved/models.py
from django.db import models

# Create your models here.

siriset_research_view_approved/views.py
from django.shortcuts import render
from django.db import connection, transaction

response = {}

def index(request):
    cursor = connection.cursor()

    if request.session['role'] == "student":
        sql = 'SELECT r.research_id, rt.research_type_name, r.topic, u.name\
            FROM approved_research a, research_type rt, research r, supervisor s, user_ u, student st\
            WHERE a.research_id = r.research_id and r.research_type_id = rt.research_type_id\
            and r.supervisor_id = s.supervisor_id and s.sso_username = u.sso_username\
            and a.student_npm = st.npm and st.sso_username = %s and a.head_program_id is not null'

        cursor.execute(sql, [request.session['user_login']])
    elif request.session['role'] == "supervisor":
        sql = 'SELECT r.research_id, u.name, sp.degree, rt.research_type_name, r.topic\
            FROM approved_research a, research_type rt, research r, user_ u, student st,\
            study_program sp, supervisor s\
            WHERE a.research_id = r.research_id and a.student_npm = st.npm\
            and st.sso_username = u.sso_username and st.program_id = sp.program_id\
            and r.research_type_id = rt.research_type_id and a.supervisor_id = s.supervisor_id\
            and s.sso_username = %s and a.head_program_id is not null'

        cursor.execute(sql, [request.session['user_login']])
    elif request.session['role'] == "head_study_program":
        sql = 'SELECT r.research_id, u.name as student_name, sp.degree, rt.research_type_name, r.topic, u2.name super_name\
            FROM approved_research a, research_type rt, research r, user_ u, user_ u2,\
            student st, study_program sp, supervisor s\
            WHERE a.research_id = r.research_id and a.student_npm = st.npm\
            and st.sso_username = u.sso_username and st.program_id = sp.program_id\
            and r.research_type_id = rt.research_type_id and a.supervisor_id = s.supervisor_id\
            and s.sso_username = u2.sso_username and a.head_program_id is not null'

        cursor.execute(sql)

    print(cursor)
    approved = dictfetchall(cursor)

    response['author'] = "si-riset"
    response['approved'] = approved
    return render(request, 'research_view_approved.html', response)

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

siriset_research_view_approved/templates/research_view_approved.html
{% extends "layout/base.html" %}

{%block content%}
  <div class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
        </br>
          <p class="lead py-0">Approved Research</p>
        </div>
      </div>
    </div>
  </div>
  <div class="px-1">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <table class="table">
            <thead> </thead>
            <tbody id="content">
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<script>
  // Show div html based on role
var role = "{{ request.session.role }}";

console.log(role)
if (role === "student"){
    $("#content").html(
        "{% for data in approved %}"
        + "<tr><td>Research Type: {{ data.research_type_name }}<br/>"
        + "Topic: {{ data.topic }}<br/>"
        + "Supervisor: {{ data.name }}</td>"
        + "<td id='logbook-button' class='d-flex justify-content-end'>"
        + "<div class='student'><button onClick=logbook({{ data.research_id }}) style='font-size: 90%'' class='btn btn-outline-primary'>Logbook</button></div>"
        + "<div class='supervisor'><button onClick=logbook({{ data.research_id }}) style='font-size: 90%'' class='btn btn-outline-primary'>Logbook</button></div>"
        + "</td></tr>{% endfor %}"
    )
    $("div.student").show();
    console.log("jalan student astaga")
} else if (role === "supervisor"){
    $("#content").html(
        "{% for data in approved %}"
        + "<tr><td style='text-transform: capitalize'>Student Name: {{ data.name }}<br/>"
        + "Degree: {{ data.degree }}<br/>"
        + "Research Type: {{ data.research_type_name }}<br/>"
        + "Topic: {{ data.topic }}"
        + "<td id='logbook-button' class='d-flex justify-content-end'>"
        + "<div class='student'><button onClick=logbook({{ data.research_id }}) style='font-size: 90%'' class='btn btn-outline-primary'>Logbook</button></div>"
        + "<div class='supervisor'><button onClick=logbook({{ data.research_id }}) style='font-size: 90%'' class='btn btn-outline-primary'>Logbook</button></div>"
        + "</td></tr>{% endfor %}"
    )
    $("div.supervisor").show();
    console.log("jalan super astaga")
} else if (role === "head_study_program"){
    $("#content").html(
        "{% for data in approved %}"
        + "<tr><td style='text-transform: capitalize'>Student Name: {{ data.student_name }}<br/>"
        + "Degree: {{ data.degree }}<br/>"
        + "Research Type: {{ data.research_type_name }}<br/>"
        + "Topic: {{ data.topic }}<br/>"
        + "Supervisor: {{ data.super_name }}</td>"
        + "</tr>{% endfor %}"
    )
    console.log("jalan head astaga")
}

var logbook = function(id) {
    $.ajax({
        method: "POST",
        url: "{% url 'logbook:view' %}",
        data: {id: id},
        dataType: 'json',
        success : function (response) {
             window.location.href = response.redirect_url;
        },
        error : function (error) {
            alert(error.responseText);
        }
    });
}

</script>
{% endblock %}