settings/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

import siriset_login.urls as login
import siriset_profile.urls as profile
import siriset_research_apply.urls as applyr
import siriset_research_approve.urls as approver
import siriset_research_view_approved.urls as viewappr
import siriset_logbook.urls as log
import siriset_defense_propose.urls as defense
import siriset_defense_schedule.urls as dsched
import siriset_scipaper_submit.urls as scipaper
import siriset_seminar_insert.urls as seminar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include((login, login), namespace='login')),
    path('profile/', include((profile, profile), namespace='profile')),
    path('apply-research/', include((applyr, applyr), namespace='apply-research')),
    path('approve-research/', include((approver, approver), namespace='approve-research')),
    path('view-approved/', include((viewappr, viewappr), namespace='view-approved')),
    path('logbook/', include((log, log), namespace='logbook')),
    path('propose-defense/', include((defense, defense), namespace='defense')),
    path('defense-schedule/', include((dsched, dsched), namespace='defense-schedule')),
    path('submit-paper/', include((scipaper, scipaper), namespace='scipaper')),
    path('insert-seminar/', include((seminar, seminar), namespace='seminar')),
    path('', RedirectView.as_view(url='login/student', permanent=True), name='index'),
]

siriset_login/urls.py
from django.conf.urls import url
from .views import index, check_data, logout

app_name = 'login'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^(?P<role>\w{0,50})/$', index, name='index'),
    url(r'^check_data/user_/$', check_data, name='check_data'),
    url(r'^logout/user_/$', logout, name='logout'),
]

siriset_login/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    sso_username = models.CharField(primary_key=True, max_length=20)
    sso_password = models.CharField(max_length=20)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    phone_no = models.CharField(max_length=15)

    class Meta:
        managed = False
        db_table = 'user_'

class Student(models.Model):
    npm = models.CharField(primary_key=True, max_length=20)
    program = models.ForeignKey('StudyProgram', models.DO_NOTHING)
    sso_username = models.ForeignKey('User', models.DO_NOTHING, db_column='sso_username')

    class Meta:
        managed = False
        db_table = 'student'

class StudyProgram(models.Model):
    program_id = models.IntegerField(primary_key=True)
    degree = models.CharField(max_length=20)
    program_name = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'study_program'


class Supervisor(models.Model):
    supervisor_id = models.IntegerField(primary_key=True)
    sso_username = models.ForeignKey('User', models.DO_NOTHING, db_column='sso_username')

    class Meta:
        managed = False
        db_table = 'supervisor'

class FacultyMember(models.Model):
    faculty_member_id = models.IntegerField(primary_key=True)
    education_level = models.CharField(max_length=20)
    sso_username = models.ForeignKey('User', models.DO_NOTHING, db_column='sso_username')

    class Meta:
        managed = False
        db_table = 'faculty_member'

class HeadStudyProgram(models.Model):
    head_id = models.IntegerField(primary_key=True)
    program = models.ForeignKey('StudyProgram', models.DO_NOTHING)
    faculty_member = models.ForeignKey(FacultyMember, models.DO_NOTHING)
    sso_username = models.ForeignKey('User', models.DO_NOTHING, db_column='sso_username')
    status = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'head_study_program'

class AcademicAdministrator(models.Model):
    admin_id = models.IntegerField(primary_key=True)
    sso_username = models.ForeignKey('User', models.DO_NOTHING, db_column='sso_username')

    class Meta:
        managed = False
        db_table = 'academic_administrator'

class ResearchManager(models.Model):
    research_manager_id = models.IntegerField(primary_key=True)
    sso_username = models.ForeignKey('User', models.DO_NOTHING, db_column='sso_username')
    status = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'research_manager'

class DefenseExaminer(models.Model):
    defense = models.ForeignKey('siriset_defense_propose.Defense', models.DO_NOTHING, primary_key=True)
    examiner = models.ForeignKey('FacultyMember', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'defense_examiner'

siriset_login/views.py
# from django.shortcuts import render
#
# response = {}
# def index(request):
#     request.session['role'] = "mahasiswa"
#     request.session['user_login'] = "raspy0"
#     return render(request, 'login.html', response)

# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.db import connection

response = {}

def index(request, role):
    response['author'] = "SIRISET"
    response['is_login'] = False
    request.session['role'] = role

    if 'user_login' in request.session:
        response['is_login'] = True
        return HttpResponseRedirect(reverse('profile:index'))
    else:
        response['is_login'] = False
        html = 'login.html'
        return render(request, html, response)

def check_data(request):
    print("check data!")
    cursor = connection.cursor()
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        cursor.execute('SELECT * FROM user_ WHERE sso_username = %s and sso_password = %s;', [username, password])
        user = cursor.fetchone()
        if user is not None: # Check data in user_
            if request.session['role'] == 'student': # Check if role student
                print("a student!")
                cursor.execute('SELECT * FROM student WHERE sso_username = %s;', [username])
                student = cursor.fetchone()
                if student is not None:
                    request.session['identity_code'] = student[0]
                    request.session['program_id'] = student[1]
                    request.session['user_login'] = username
                else:
                    return HttpResponseRedirect(reverse('login:index', kwargs={'role':'student'}))

            elif request.session['role'] == 'supervisor': # Check if role supervisor
                cursor.execute('SELECT * FROM supervisor WHERE sso_username = %s;', [username])
                supervisor = cursor.fetchone()
                if supervisor is not None:
                    request.session['identity_code'] = supervisor[0]
                    request.session['user_login'] = username
                else:
                    return HttpResponseRedirect(reverse('login:index', kwargs={'role':'supervisor'}))

            elif request.session['role'] == 'research_manager': # Check if role research_manager
                cursor.execute('SELECT * FROM research_manager WHERE sso_username = %s;', [username])
                research_manager = cursor.fetchone()
                if research_manager is not None:
                    request.session['identity_code'] = research_manager[0]
                    request.session['status'] = research_manager[2]
                    request.session['user_login'] = username
                else:
                    return HttpResponseRedirect(reverse('login:index', kwargs={'role':'research_manager'}))

            elif request.session['role'] == 'academic_administrator': # Check if academic_administrator
                cursor.execute('SELECT * FROM academic_administrator WHERE sso_username = %s;', [username])
                academic_administrator = cursor.fetchone()
                if academic_administrator is not None:
                    request.session['identity_code'] = academic_administrator[0]
                    request.session['user_login'] = username
                else:
                    return HttpResponseRedirect(reverse('login:index', kwargs={'role':'academic_administrator'}))

            elif request.session['role'] == 'head_study_program': # Check if role faculty_member
                cursor.execute('SELECT * FROM faculty_member WHERE sso_username = %s;', [username])
                faculty_member = cursor.fetchone()
                if faculty_member is not None:
                    cursor.execute('SELECT * FROM head_study_program WHERE faculty_member_id = %s;', [faculty_member[0]])
                    head_study_program = cursor.fetchone()
                    if head_study_program is not None:
                        request.session['identity_code'] = head_study_program[0]
                        request.session['program_id'] = head_study_program[1]
                        request.session['faculty_member_id'] = head_study_program[2]
                        request.session['status'] = head_study_program[4]
                        request.session['user_login'] = username
                else:
                    return HttpResponseRedirect(reverse('login:index', kwargs={'role':'head_study_program'}))

        else: # redirect if not user_
            return HttpResponseRedirect(reverse('login:index', kwargs={'role':request.session['role']}))

    return HttpResponseRedirect(reverse('profile:index'))

def logout(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('login:index', kwargs={'role':'student'}))

def authenticate(request):
	return ('user_login' in request.session.keys())

siriset_login/templates/partials/footer.html
<!-- templates/lab_5/partials/footer.html -->
<!-- TODO, CREATE THIS FILE AND ADD copyright symbol -->
</br>
<p style='font-size: 80%'>Made by Bagus, Danaz, Aghnia</p>

<style>
footer p {
    padding-top: 0px;
    padding-bottom: 30px;
    bottom:0px;
    margin: 0 auto
    position: absolute;
    text-align: center;
    flex: 0 0 50px;
    margin-top: auto;
}

footer {
    position:relative;
    height: auto;
}
</style>

siriset_login/templates/partials/header.html
{% load staticfiles %}
{% load static %}
<!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url "profile:index" %}">SI-RISET</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar3SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-center" id="navbar3SupportedContent">
        <ul id="navbar-content" class="navbar-nav">
        </ul>
        <a style="font-size: 90%" class="ml-3 btn navbar-btn btn-primary" id="logout" href="{% url "login:logout" %}">Logout</a>
      </div>
    </div>
  </nav>

  <script>
  window.onload=function() {
      var role = "{{ request.session.role }}";

      if(!"{{ request.session.user_login}}") {
          $("#logout").hide();
          $("#navbar-content").hide();
      }

      if (role === "student") {
          $("#navbar-content").html(
              '<li class="nav-item px-3">'
                + '<a class="nav-link" href="{% url "profile:index" %}">Profile</a></li>'
              + '<li class="nav-item dropdown px-3">'
                + '<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Research&nbsp;</a>'
                + '<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">'
                  + '<a class="dropdown-item" href="{% url "apply-research:index" %}">Apply Research</a>'
                  + '<a class="dropdown-item" href="{% url "view-approved:index" %}">View Approved Research</a></div></li>'
              + '<li class="nav-item px-3">'
                + '<a class="nav-link" href="{% url "defense:index" %}">Defense</a></li>'
              + '<li class="nav-item px-3">'
                + '<a class="nav-link" href="{% url "scipaper:index" %}">Scientific Paper</a></li>'
          )
      } else if (role === 'supervisor' || role === 'head_study_program') {
          $("#navbar-content").html(
              '<li class="nav-item px-3">'
                + '<a class="nav-link" href="{% url "profile:index" %}">Profile</a></li>'
              + '<li class="nav-item dropdown px-3">'
                + '<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Research&nbsp;</a>'
                + '<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">'
                  + '<a class="dropdown-item" href="{% url "approve-research:index" %}">Research Application</a>'
                  + '<a class="dropdown-item" href="{% url "view-approved:index" %}">View Approved Research</a></div></li>'
          )
      } else if (role === 'research_manager') {
          $("#navbar-content").html(
              '<li class="nav-item px-3">'
                + '<a class="nav-link" href="{% url "profile:index" %}">Profile</a></li>'
              + '<li class="nav-item dropdown px-3">'
                + '<a class="nav-link" href="{% url "seminar:index" %}">Seminar Reboan</a></li>'
          )
      } else if (role === 'academic_administrator') {
          $("#navbar-content").html(
              '<li class="nav-item px-3">'
                + '<a class="nav-link" href="{% url "profile:index" %}">Profile</a></li>'
              + '<li class="nav-item dropdown px-3">'
                + '<a class="nav-link" href="{% url "defense-schedule:index" %}">Defense Schedule</a></li>'
          )
      }
  };

  </script>