settings/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

import siriset_login.urls as login
import siriset_profile.urls as profile
import siriset_research_apply.urls as applyr
import siriset_research_approve.urls as approver
import siriset_research_view_approved.urls as viewappr
import siriset_logbook.urls as log
import siriset_defense_propose.urls as defense
import siriset_defense_schedule.urls as dsched
import siriset_scipaper_submit.urls as scipaper
import siriset_seminar_insert.urls as seminar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include((login, login), namespace='login')),
    path('profile/', include((profile, profile), namespace='profile')),
    path('apply-research/', include((applyr, applyr), namespace='apply-research')),
    path('approve-research/', include((approver, approver), namespace='approve-research')),
    path('view-approved/', include((viewappr, viewappr), namespace='view-approved')),
    path('logbook/', include((log, log), namespace='logbook')),
    path('propose-defense/', include((defense, defense), namespace='defense')),
    path('defense-schedule/', include((dsched, dsched), namespace='defense-schedule')),
    path('submit-paper/', include((scipaper, scipaper), namespace='scipaper')),
    path('insert-seminar/', include((seminar, seminar), namespace='seminar')),
    path('', RedirectView.as_view(url='login/student', permanent=True), name='index'),
]

siriset_research_approve/urls.py
from django.conf.urls import url
from .views import index, approve, reject
#url for app

app_name = 'approver'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^approve/$', approve, name='approve'),
    url(r'^reject/$', reject, name='reject'),
]

siriset_research_approve/models.py
from django.db import models

# Create your models here.
class ApprovedResearch(models.Model):
    approval_id = models.IntegerField(primary_key=True)
    research = models.ForeignKey('siriset_research_apply.Research', models.DO_NOTHING)
    student_npm = models.ForeignKey('siriset_login.Student', models.DO_NOTHING, db_column='student_npm')
    supervisor = models.ForeignKey('siriset_login.Supervisor', models.DO_NOTHING)
    head_program = models.ForeignKey('siriset_login.HeadStudyProgram', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'approved_research'

siriset_research_approve/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.db import connection, transaction

response = {}

def index(request):
    cursor = connection.cursor()
    if request.session['role'] == "supervisor":
        sql = 'SELECT r.research_id, r.student_npm, rt.research_type_name, r.topic, r.motivation\
            FROM research r, research_type rt, supervisor s\
            WHERE r.research_type_id = rt.research_type_id and r.supervisor_id = s.supervisor_id\
            and s.sso_username = %s and not exists (SELECT 1 FROM approved_research a\
            WHERE a.research_id = r.research_id)'
        cursor.execute(sql, [request.session['user_login']])
    elif request.session['role'] == "head_study_program":
        sql = 'SELECT a.research_id, a.student_npm, u.name, rt.research_type_name, r.topic, r.motivation\
            FROM approved_research a, research r, research_type rt, supervisor s, user_ u\
            WHERE a.research_id = r.research_id and r.research_type_id = rt.research_type_id\
            and a.supervisor_id = s.supervisor_id and s.sso_username = u.sso_username and a.head_program_id is null'
        cursor.execute(sql)

    research = dictfetchall(cursor)

    response['author'] = "si-riset"
    response['research'] = research
    return render(request, 'research_approve.html', response)

@csrf_exempt
def approve(request):
    if request.method == 'POST':
        research_id = request.POST['id']

    cursor = connection.cursor()

    if request.session['role'] == "supervisor" :
        sql = 'SELECT r.student_npm, r.supervisor_id FROM research r\
            WHERE r.research_id = %s'

        cursor.execute(sql, [research_id])
        research = dictfetchall(cursor)

        sql = "INSERT INTO approved_research (approval_id, research_id, student_npm,\
            supervisor_id, head_program_id) VALUES (nextval('ApprovalId'), %s, %s, %s, null)"

        cursor.execute(sql, [research_id, research[0]['student_npm'],\
            research[0]['supervisor_id']])

    elif request.session['role'] == "head_study_program":
        sql = 'UPDATE approved_research SET head_program_id = 1 WHERE research_id = %s'

        cursor.execute(sql, [research_id])

    data = {'id': research_id}
    return JsonResponse(data)

@csrf_exempt
def reject(request):
    if request.method == 'POST':
        research_id = request.POST['id']

    cursor = connection.cursor()

    if request.session['role'] == "supervisor" :
        sql = 'DELETE FROM research WHERE research_id = %s'

        cursor.execute(sql, [research_id])

    elif request.session['role'] == "head_study_program":
        sql = 'DELETE FROM approved_research WHERE research_id = %s'
        cursor.execute(sql, [research_id])
        sql = 'DELETE FROM research WHERE research_id = %s'
        cursor.execute(sql, [research_id])

    data = {'id': research_id}
    return JsonResponse(data)

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

siriset_research_approve/templates/research_approve.html
{% extends "layout/base.html" %}

{% load staticfiles %}
{% load static %}

{%block content%}
  <div class="py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
        </br>
          <p class="lead py-0">New Application</p>
        </div>
      </div>
    </div>
  </div>
  <div class="px-1">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <table class="table">
            <thead> </thead>
            <tbody>
              <tr>
                  <th>Student ID</th>
                  <th>Research Type</th>
                  <th>Topic</th>
                  <th>Motivation</th>
                  <th>Supervisor</th>
                  <th></th>
              </tr>
              {% for data in research %}
              <tr id="{{ data.research_id }}">
                  <td>{{ data.student_npm }}</td>
                  <td>{{ data.research_type_name }}</td>
                  <td>{{ data.topic }}</td>
                  <td>{{ data.motivation }}</td>
                  <td>{{ data.name }}</td>
                  <td class="d-flex justify-content-end">
                      <div class="supervisor"><button onClick=approve({{ data.research_id }}) style="font-size: 90%" class="btn btn-outline-primary">Approve</button></div>
                      <div class="head"><button onClick=approve({{ data.research_id }}) style="font-size: 90%" class="btn btn-outline-primary">Approve</button></div>
                      <div class="supervisor"><button onClick=reject({{ data.research_id }}) style="font-size: 90%; margin-left:10px" class="btn btn-outline-primary">Reject</button></div>
                      <div class="head"><button onClick=reject({{ data.research_id }}) style="font-size: 90%; margin-left:10px" class="btn btn-outline-primary">Reject</button></div>
                  </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

<script>

// Show div html based on role
var role = "{{ request.session.role }}";
console.log(role)
if (role === "supervisor"){
    $("div.supervisor").show();
    $('td:nth-child(5),th:nth-child(5)').hide();
    console.log("super")
} else if (role === "head_study_program"){
    $("div.head").show();
}

var approve = function(id) {
    $.ajax({
        method: "POST",
        url: "{% url 'approve-research:approve' %}",
        data: {id: id},
        dataType: 'json',
        success : function (response) {
            console.log("ok");
            $('#' + response.id).remove();
        },
        error : function (error) {
            alert(error.responseText);
        }
    });
}

var reject = function(id) {
    $.ajax({
        method: "POST",
        url: "{% url 'approve-research:reject' %}",
        data: {id: id},
        dataType: 'json',
        success : function (response) {
            console.log("ok");
            $('#' + response.id).remove();
        },
        error : function (error) {
            alert(error.responseText);
        }
    });
}


</script>
{% endblock %}